pipeline {
  agent {
    docker { 
      image 'node:16-alpine' 
      args '-u root --privileged'
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
